apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-velero-label
  annotations:
    policies.kyverno.io/title: Add Label for backup
    policies.kyverno.io/category: Backup
    policies.kyverno.io/subject: Labels
    policies.kyverno.io/severity: low
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      By default, add a label to say that you want to backup your ressources
spec:
  rules:
  - name: add-velero-label
    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            saved-by-velero: "true"
    {{- if .Values.excludedNamespaces }}
    {{- if gt (len .Values.excludedNamespaces) 0 }}
    exclude:
      any:
      - resources:
          namespaces:
            {{- range .Values.excludedNamespaces }}
            - "{{ . }}"
            {{- end }}
    {{- end }}
    {{- end }}
