{{- if .Values.netpol_cnpg.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-networkpolicy-cnpg-operator
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy, NetworkPolicy
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/severity: low
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      By default, Kubernetes allows communications across all Pods within a cluster. allow from ingress
spec:
  generateExisting: true
  rules:
  - name: allow-from-cnpg-operator
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: allow-from-cnpg-operator
      namespace: "{{`{{ request.object.metadata.name }}`}}"
      synchronize: true
      data:
        spec:
          podSelector: {}
          ingress:
          - from:
            - namespaceSelector:
                matchExpressions:
                - key: kubernetes.io/metadata.name
                  operator: In
                  values: {{ .Values.netpol_cnpg.namespace }}
    skipBackgroundRequests: true
    exclude:
      any:
      - resources:
          namespaces:
            {{- range concat .Values.excludedNamespaces .Values.extraExcludedNamespaces }}
            - "{{ . }}"
            {{- end }}
{{- end }}