apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset-of-appset
  namespace: infra-argo
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/cloud-pi-native/cluster-automation.git
        revision: main
        files:
        - path: "clusters/**/values-test.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'test-cluster-{{.appset.clustername}}'
    spec:
      project: '{{ .appset.clustername }}'
      sources:
      - repoURL: https://github.com/cloud-pi-native/infra-app.git
        targetRevision: '{{ .appset.default.branch }}'
        path: apps/appset
        helm:
          valueFiles: 
            - "$cluster/clusters/{{ .appset.clustername }}/values-test.yaml"
      - ref: cluster
        repoURL:  "https://github.com/cloud-pi-native/cluster-automation.git"
        targetRevision: "main"          
      destination:
        name: in-cluster
        namespace: infra-argo
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
