---
apiVersion: v2
name: mimir
type: application
version: 0.1.0
appVersion: "2.9.0"
dependencies:
  - name: etcd
    version: 9.0.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: etcd.enabled
  - name: rollout-operator
    repository: https://grafana.github.io/helm-charts
    version: 0.8.0
  - name: mimir-distributed
    alias: mimir
    version: 5.1.0-weekly.251
    repository: https://grafana.github.io/helm-charts