sops:
  fullnameOverride: sops
  replicaCount: 2

  extraEnv:
  - name: "SOPS_AGE_KEY_FILE"
    value: "/etc/sops-age-key-file/key"

  secretsAsFiles:
  - name: "sops-age-key-file"
    mountPath: "/etc/sops-age-key-file/"
    secretName: "sops-age-key-file"
