apiVersion: v2
type: application
name: teleport
version: 16.2.0
appVersion: "16.2.0"
dependencies:
- name: teleport-cluster
  alias: server
  version: 16.2.0
  repository: https://charts.releases.teleport.dev
  condition: server.enabled
- name: teleport-kube-agent
  alias: client
  version: 16.2.0
  repository: https://charts.releases.teleport.dev
  condition: client.enabled