kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ include "velero.namespace" . }}
  labels:
    app: {{ .Values.serviceAccount }}


---
apiVersion: clusterroles.rbac.authorization.k8s.io
kind: ClusterRole
metadata:
  name: cluster-{{ .Values.serviceAccount }}
  labels:
    app: {{ .Values.serviceAccount }}
rules:
- apiGroups: [""]
  resources:
  - "nodes"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups:
  - velero.io
  resources:
  - schedules
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch


---
kind: ClusterRoleBinding
apiVersion: clusterrolebindings.rbac.authorization.k8s.io
metadata:
  name: {{ .Values.serviceAccount }}
  labels:
    app: {{ .Values.serviceAccount }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ include "velero.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-{{ .Values.serviceAccount }}
