kind: ServiceAccount
apiVersion: v1
metadata:
  name: projects-backup
  namespace: {{ include "velero.namespace" . }}
  labels:
    app: projects-backup


---
apiVersion: clusterroles.rbac.authorization.k8s.io
kind: ClusterRole
metadata:
  name: cluster-projects-backup
  labels:
    app: projects-backup
rules:
- apiGroups: [""]
  resources:
  - "nodes"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups:
  - velero.io
  resources:
  - schedules
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch


---
kind: ClusterRoleBinding
apiVersion: clusterrolebindings.rbac.authorization.k8s.io
metadata:
  name: projects-backup
  labels:
    app: projects-backup
subjects:
- kind: ServiceAccount
  name: projects-backup
  namespace: {{ include "velero.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-projects-backup


#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: projects-backup-privileged
#  namespace: {{ include "velero.namespace" . }}
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: system:openshift:scc:privileged
#subjects:
#- kind: ServiceAccount
#  name: projects-backup
#  namespace: {{ include "velero.namespace" . }}