{{- if .Values.volumesnapshotclass.enabled }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: csi-vsphere-vsc
deletionPolicy: Delete
driver: csi.vsphere.vmware.com
{{- end }}