appset:
  clustername: clustertest
  type: kube  # Peut être 'okd', 'rke', ou 'kube'
  default:
    ServerSideApply: true
    CreateNamespace: true
    branch: "main"
    repoUrl: "https://github.com/cloud-pi-native/infra-app.git"
    valuesRepoUrl: "https://github.com/cloud-pi-native/cluster-automation.git"
    valuesRepoUrl1: "https://github.com/cloud-pi-native/cluster-automation.git"
    valuesRepoUrlBranch: "main"
    valuesRepoUrlBranch1: "main"
    syncPolicy:
      prune: true
      selfHeal: true
      autoSync: true


  # Composants personnalisés à ajouter ou surcharger
  customComponents: {}
#    nginx:
#      namespace: infra-nginx-system
#      branch: "custom-branch"

  # Composants par type de cluster, avec des maps
  components:
    kube:
      cert-manager:g
        namespace: cert-manager
      cortex:
        namespace: cortex
      falco:
        namespace: falco
      rbac-manager:
        namespace: rbac-manager
      sops:
        namespace: sops
      teleport:
        namespace: teleport
      trivy-operator:
        namespace: trivy-operator
      velero:
        namespace: velero
      vso:
        namespace: vso
      